### ISSUE TITLE
Update Frontend to Implement Homepage and Coding page 

### ISSUE THREAD

**Issue by lleyi0606** [CS3219-AY2324S1/ay2324s1-course-assessment-g25#52]
Will be updating 
- the landing page (after sign in) to a homepage resembling leetcode's 
- move add questions into a separate page accessible by the side bar 
- implement the page where the coding and matching will happen

**Comment by wxy1203** [comment]
Resolves in #64

**Comment by wxy1203** [comment]
Resolves in #64
